### ISSUE TITLE
Can you provide more info in the readme.md? 

### ISSUE THREAD

**Issue by PaLiNYG96** [Hanif-adedotun/crypto-prediction-lstm-bert#3]
Any way you can provide some more information about what this project is, how it works, how to run it, etc? 
Thanks.

**Comment by Hanif-adedotun** [comment]
Hello there, apologies, but I provided a more verbose explanation on the project in this repository https://github.com/Hanif-adedotun/ML-Series/tree/main/BTC-PREDICTION

**Comment by PaLiNYG96** [comment]
Thank you for the quick response.
